### ISSUE TITLE
"description" field is not generated correctly on schemas

### ISSUE THREAD

**Issue by haowjernseek** [samchungy/zod-openapi#199]
Taking the examples from the README, if we look at the `jobId` parameter on the swagger editor, there's no description, but the yaml file does contain the `description` field. 

```
parameters:
  - in: path
    name: jobId
    schema:
      type: string
      description: Job ID
      example: '12345'
```

![image](https://github.com/samchungy/zod-openapi/assets/133635458/aea340c6-7cf9-4c69-ba67-8b6759768a78)

After playing around with this, turns out if the `description` field is moved out of the 'schema' object, then it displays correctly, i.e.
```
parameters:
  - in: path
    name: jobId
    description: Job ID
    schema:
      type: string
      example: '12345'
```

![image](https://github.com/samchungy/zod-openapi/assets/133635458/874810d6-ce00-4cee-8587-d98879a28af6)

Could you help look into this please?
